### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by Uwah** [LaoLeo/multi-pages-vue-ssr#19]
把代码down下来后运行报
ERROR in ./src/views/HomeView.vue
Module build failed: TypeError: Cannot read property 'parseComponent' of undefined
    at parse (E:\ssr-multi\multi-pages-vue-ssr-master\node_modules\_@vue_component-compiler-utils@3.3.0@@vue\component-compiler-utils\dist\parse.js:15:23)
    at Object.module.exports (E:\ssr-multi\multi-pages-vue-ssr-master\node_modules\_vue-loader@15.9.8@vue-loader\lib\index.js:67:22)
 @ ./src/router/index.js 21:11-42
 @ ./src/pages/admin/index.js
 @ ./src/pages/admin/entry-client.js

ERROR in ./src/views/AdminView.vue
Module build failed: TypeError: Cannot read property 'parseComponent' of undefined

**Comment by LaoLeo** [comment]
包版本的问题，将@vue/component-compiler-utils包换成2.6.0。
